from decorations.AncientSkull import AncientSkull
from decorations.CornflowerBed import CornflowerBed
from decorations.MightyHeroStatue import MightyHeroStatue
from decorations.MightyStatue import MightyStatue
from decorations.PekkaStatue import PekkaStatue
from decorations.PirateFlag import PirateFlag
from decorations.PointFlag import PointFlag
from decorations.RallyFlag import RallyFlag
from decorations.SunflowerBed import SunflowerBed
from decorations.Torch import Torch
from decorations.WeatherVane import WeatherVane
from decorations.WhiteFlag import WhiteFlag
